### ISSUE TITLE
"The given data was not valid JSON." and crashes app

### ISSUE THREAD

**Issue by sidc0des** [torusresearch/torus-direct-flutter-sdk#6]
TorusUtils/TorusUtils+extension.swift:641: Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0})))

while running this function on iOS

TorusCredentials creds = await TorusDirect.getTorusKey(
        idToken: idToken,
        verifier: verifier,
        verifierId: verifierId,
      );

flutter => 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0 21A5534d darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

• No issues found!

environment:
  sdk: ">=2.12.0 <3.0.0

using repo directly in pubspec.yaml because pub.dev version don't include this function

  torus_direct:
    git:
      url: https://github.com/torusresearch/torus-direct-flutter-sdk

**Comment by chaitanyapotti** [comment]
Fixed
